[build]
  functions = "functions"

[functions]
  # Specify timeout within a block
  [functions.timeout]
  value = 30  # Timeout in seconds

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
